### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ascherld** [armageddon-mudlet/armageddon-mudlet#1]
I would like to know if this code is available for public use or not. It was last touched three years ago, and I'd like to help provide fixes to update the software or get licensing permission to update the code.

**Comment by AlysCole** [comment]
Sorry about the late response. Just added a license. Please feel free to use the code and/or make updates to this repo. I'll try to approve PRs, but can also add you as a member to this GitHub org if you'd like, since I can't promise to be active.
